spring:
    datasource:
        url: jdbc:mysql://172.17.0.2:3306/cars
        username: root
        password: 12345

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                jdbc:
                    time_zone: UTC
